#!/usr/bin/python3
try:
    from lxml import etree
except ImportError:
    print(traceback.format_exc())
    print()
    print("HINT: Instale el paquete python3-lxml e intente de nuevo")
    print()
    sys.exit(32)
try:
    import psycopg2
except ImportError:
    print(traceback.format_exc())
    print()
    print("HINT: Instale el paquete python3-psycopg2 e intente de nuevo")
    print()
    sys.exit(32)

try:
    import sip
    # switch on QVariant in Python3
    sip.setapi('QVariant', 1)
    sip.setapi('QString', 1)

    from PyQt4 import QtGui, QtCore, uic
except ImportError:
    print(traceback.format_exc())
    print()
    print("HINT: Instale el paquete python3-pyqt4 e intente de nuevo")
    print()
    sys.exit(32)

from PyQt4 import QtGui, QtCore
from pineboolib.fllegacy.FLSettings import FLSettings

import pineboolib.emptyscript
from pineboolib import decorators



from pineboolib.utils import filedir, one, Struct, XMLStruct
Qt = QtCore.Qt


import sys, re, traceback, os, gc


import pineboolib.flparser.postparse
app = QtGui.QApplication(sys.argv)

if __name__ == "__main__":
    pineboolib.flparser.postparse.main()
