# lextab.py. This file automatically created by PLY (version 3.9). Don't edit!
_tabversion   = '3.8'
_lextokens    = set(('GE', 'EXTENDS', 'EQQ', 'NEW', 'RBRACKET', 'SEMI', 'CCONST', 'CONTINUE', 'MODEQUAL', 'PLUSEQUAL', 'LBRACE', 'DIVEQUAL', 'VAR', 'CONDITIONAL1', 'XOR', 'MOD', 'TYPEOF', 'LOR', 'DOCSTRINGOPEN', 'EQUALS', 'NEQ', 'WHILE', 'COLON', 'DELETE', 'FUNCTION', 'COMMA', 'COMMENTCLOSE', 'SQOUTE', 'SWITCH', 'CASE', 'DIVIDE', 'DEFAULT', 'LE', 'CLASS', 'RPAREN', 'RBRACE', 'CONST', 'LAND', 'IN', 'CATCH', 'DOLLAR', 'RETURN', 'ID', 'NE', 'MINUSEQUAL', 'OR', 'PLUS', 'EQ', 'DQOUTE', 'TRY', 'BACKSLASH', 'SCONST', 'AND', 'FCONST', 'AT', 'THROW', 'MINUSMINUS', 'ELSE', 'ICONST', 'PLUSPLUS', 'LNOT', 'BREAK', 'LT', 'FOR', 'IF', 'LSHIFT', 'TIMES', 'PERIOD', 'LBRACKET', 'DO', 'RSHIFT', 'WITH', 'LPAREN', 'GT', 'STATIC', 'TIMESEQUAL', 'MINUS'))
_lexreflags   = 0
_lexliterals  = ''
_lexstateinfo = {'INITIAL': 'inclusive'}
_lexstatere   = {'INITIAL': [('(?P<t_NEWLINE>\\n+)|(?P<t_ID>[A-Za-z_]+[\\w_]*)|(?P<t_comment>(/\\*( |\\*\\*)(.|\\n)*?\\*/)|(//.*))|(?P<t_DOCSTRINGOPEN>/\\*\\*[ ]+)|(?P<t_preprocessor>\\#(.)*?\\n)|(?P<t_FCONST>((\\d+)(\\.\\d+)(e(\\+|-)?(\\d+))? | (\\d+)e(\\+|-)?(\\d+))([lL]|[fF])?)|(?P<t_ICONST>\\d+([uU]|[lL]|[uU][lL]|[lL][uU])?)|(?P<t_SCONST>\\"([^\\"\\\\\\n]|(\\\\.)|\\\\\\n)*?\\")|(?P<t_CCONST>\\\'([^\\\'\\\\\\n]|(\\\\.)|\\\\\\n)*?\\\')|(?P<t_LOR>\\|\\|)|(?P<t_PLUSPLUS>\\+\\+)|(?P<t_EQQ>===)|(?P<t_NEQ>!==)|(?P<t_TIMESEQUAL>\\*=)|(?P<t_PLUSEQUAL>\\+=)|(?P<t_COMMENTCLOSE>\\*/)|(?P<t_BACKSLASH>\\\\)|(?P<t_DOLLAR>\\$)|(?P<t_PLUS>\\+)|(?P<t_TIMES>\\*)|(?P<t_OR>\\|)|(?P<t_XOR>\\^)|(?P<t_LSHIFT><<)|(?P<t_RSHIFT>>>)|(?P<t_LAND>&&)|(?P<t_LE><=)|(?P<t_GE>>=)|(?P<t_EQ>==)|(?P<t_NE>!=)|(?P<t_CONDITIONAL1>\\?)|(?P<t_DIVEQUAL>/=)|(?P<t_MODEQUAL>%=)|(?P<t_MINUSEQUAL>-=)|(?P<t_MINUSMINUS>--)|(?P<t_LPAREN>\\()|(?P<t_RPAREN>\\))|(?P<t_LBRACKET>\\[)|(?P<t_RBRACKET>\\])|(?P<t_LBRACE>\\{)|(?P<t_RBRACE>\\})|(?P<t_PERIOD>\\.)|(?P<t_SQOUTE>\')|(?P<t_DQOUTE>")|(?P<t_MINUS>-)|(?P<t_DIVIDE>/)|(?P<t_MOD>%)|(?P<t_AND>&)|(?P<t_LNOT>!)|(?P<t_LT><)|(?P<t_GT>>)|(?P<t_EQUALS>=)|(?P<t_COMMA>,)|(?P<t_SEMI>;)|(?P<t_COLON>:)|(?P<t_AT>@)', [None, ('t_NEWLINE', 'NEWLINE'), ('t_ID', 'ID'), ('t_comment', 'comment'), None, None, None, None, ('t_DOCSTRINGOPEN', 'DOCSTRINGOPEN'), ('t_preprocessor', 'preprocessor'), None, (None, 'FCONST'), None, None, None, None, None, None, None, None, None, None, (None, 'ICONST'), None, (None, 'SCONST'), None, None, (None, 'CCONST'), None, None, (None, 'LOR'), (None, 'PLUSPLUS'), (None, 'EQQ'), (None, 'NEQ'), (None, 'TIMESEQUAL'), (None, 'PLUSEQUAL'), (None, 'COMMENTCLOSE'), (None, 'BACKSLASH'), (None, 'DOLLAR'), (None, 'PLUS'), (None, 'TIMES'), (None, 'OR'), (None, 'XOR'), (None, 'LSHIFT'), (None, 'RSHIFT'), (None, 'LAND'), (None, 'LE'), (None, 'GE'), (None, 'EQ'), (None, 'NE'), (None, 'CONDITIONAL1'), (None, 'DIVEQUAL'), (None, 'MODEQUAL'), (None, 'MINUSEQUAL'), (None, 'MINUSMINUS'), (None, 'LPAREN'), (None, 'RPAREN'), (None, 'LBRACKET'), (None, 'RBRACKET'), (None, 'LBRACE'), (None, 'RBRACE'), (None, 'PERIOD'), (None, 'SQOUTE'), (None, 'DQOUTE'), (None, 'MINUS'), (None, 'DIVIDE'), (None, 'MOD'), (None, 'AND'), (None, 'LNOT'), (None, 'LT'), (None, 'GT'), (None, 'EQUALS'), (None, 'COMMA'), (None, 'SEMI'), (None, 'COLON'), (None, 'AT')])]}
_lexstateignore = {'INITIAL': ' \r\t\x0c'}
_lexstateerrorf = {'INITIAL': 't_error'}
_lexstateeoff = {}
