from .iformdb import IFormDB
from typing import Any, Callable


class IFormRecordDB(IFormDB):
    __init__: Callable
    # def __init__(self, parent_or_cursor, action, load=False) -> None:
    #     ...

    def setMainWidget(self, w=None):
        ...

    def setCaptionWidget(self, text=None) -> None:
        ...

    def formClassName(self):
        ...

    def initForm(self):
        ...

    def loadControls(self):
        ...

    def formName(self):
        ...

    def closeEvent(self, e):
        ...

    def validateForm(self) -> Any:
        ...

    def acceptedForm(self) -> None:
        ...

    def afterCommitBuffer(self) -> None:
        ...

    def afterCommitTransaction(self) -> None:
        ...

    def canceledForm(self) -> None:
        ...

    def accept(self):
        ...

    def acceptContinue(self):
        ...

    def reject(self):
        ...

    def script(self):
        ...

    def firstRecord(self):
        ...

    def previousRecord(self):
        ...

    def nextRecord(self):
        ...

    def lastRecord(self):
        ...

    def disablePushButtonCancel(self):
        ...

    def show(self):
        ...

    def inicializeControls(self) -> None:
        ...

    def show_and_wait(self) -> None:
        ...

    def hide(self) -> None:
        ...
